dogbuddy_task/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views
from dogbuddy_messaging.forms import LoginForm
from dogbuddy_messaging import views as dogbuddy_messaging_views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    # Examples:
    # url(r'^$', 'django_custom_user_example.views.home', name='home'),
    # url(r'^django_custom_user_example/',
    # include('django_custom_user_example.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/',
    # include('django.contrib.admindocs.urls')),
    url(r'^$', dogbuddy_messaging_views.messages, name='messages'),
    url(r'^friends/$', dogbuddy_messaging_views.friends, name='friends'),
    url(r'^write_message/$', dogbuddy_messaging_views.write_message, name='write_message'),
    url(r'^send_message/$', dogbuddy_messaging_views.send_message, name='send_message'),
    url(r'^conversation/(?P<conversation_id>\d+)/$', dogbuddy_messaging_views.show_conversation, name='show_conversation'),

    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    url(r'^register/$', dogbuddy_messaging_views.register_user, name='register'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

dogbuddy_messaging/models.py
from __future__ import unicode_literals
import re
from django.conf import settings
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
                                        UserManager)
from django.core.mail import send_mail
from django.core import validators
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.utils.http import urlquote

# Create your models here.


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    A custom user class that basically mirrors Django's `AbstractUser` class
    and doesn't force `first_name` or `last_name` with sensibilities for
    international names.

    http://www.w3.org/International/questions/qa-personal-names
    """
    username = models.CharField(_('username'), max_length=30, unique=True,
                                help_text=_('Required. 30 characters or fewer. Letters, numbers and '
                                            '@/./+/-/_ characters'),
                                validators=[
        validators.RegexValidator(re.compile(
            '^[\w.@+-]+$'), _('Enter a valid username.'), 'invalid')
    ])
    full_name = models.CharField(_('full name'), max_length=254, blank=True)
    short_name = models.CharField(_('short name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    is_staff = models.BooleanField(_('staff status'), default=True,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __unicode__(self):
        return self.username

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.username)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = self.full_name
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.short_name.strip()

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])


class Contact(models.Model):

    name = models.CharField(max_length=200)
    email = models.EmailField(_('email address'), max_length=254)
    contact_owner = models.ForeignKey(settings.AUTH_USER_MODEL)


class Conversation(models.Model):
    created_at = models.DateTimeField(default=timezone.now)


class UserConversationLink(models.Model):
    """
    this class links a user to a conversation. I have decided to make the user's email the primary key
    for the user. --> A user is linked to a conversation through his email. I do not link the user to the
    conversation through the models.ForeignKey(settings.AUTH_USER_MODEL) because the user I am writing the
    message to may not be an actual user yet. He might sign up after the message was sent to him with
    the email that is saved here. This way conversations can be assigned to users that were created before
    the user became an actual user of the platform.
    """
    email = models.EmailField(_('email address'), max_length=254)
    conversation = models.ForeignKey(Conversation)


class Message(models.Model):
    conversation = models.ForeignKey(Conversation)
    from_email = models.EmailField(max_length=254)
    to_email = models.EmailField(max_length=254)
    message_text = models.TextField(blank=True, max_length=1500)
    was_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)

templates/auth_base.html
<!DOCTYPE html>
<html>

{% load staticfiles %}


<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/dogbuddy.messaging.css' %}" rel="stylesheet">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src = "{% static 'js/dogbuddy.messaging.js' %}"></script>

    {% block custom_javascript %}

    {% endblock %}

    <title>Basket Friends</title>

</head>

<body>


{% block content %}
{% endblock %}



</body>

</html>

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/dogbuddy.messaging.css' %}" rel="stylesheet">
    <title>Basket Friends</title>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="{% static 'js/dogbuddy.messaging.js' %}"></script>

    {% block custom_javascript %}

    {% endblock %}

</head>

<body>
<div id="nav">
    <ul class="base-topnav" id="base-navbar">
        <li><a href="/" class="">Messages</a></li>
        <li><a href="/friends/" class="base-active">Friends</a></li>
        <li class="push-right"><a href="/logout/" class="">Logout</a></li>

    </ul>

</div>
<div class="push-down-main-content"> <!-- pushes down the content a little bit, how much depends on the
                                        screen size -->
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/conversation.html
{% extends 'base.html' %}

back-to-messages-link

{% block custom_javascript %}
<script>
    $(document).ready(function () {
      // the link shrinking happens in dogbuddy.messaging.js
    });
</script>
{% endblock %}


{% block content %}

<div class="row">
    <div class="col-3 move-down-back-button-on-small-screen">
        <!-- placeholder div -->
        <a class="messages-back-link" id="back-to-messages-link" href="/"><< Back</a>
    </div>

    <div class="col-6">
        <h1 style="text-align: center; margin-bottom: 5px">Conversation with {{ conversation_partner }}</h1>
        {% for message in all_messages %}

        {% if message.sender == 'Me' %}
                <div style="text-align: center">
                {{ message.sender }}
                           <div class="talk-bubble tri-right left-in">
                  <div class="talktext">
                    <p>{{ message.message_text }}</p>
                  </div>
                </div>
        </div>

        {% else %}
        <div style="text-align: center">
            <div class="talk-bubble tri-right round right-in">
              <div class="talktext">
                <p>{{ message.message_text }}</p>
              </div>
            </div>
            {{ message.sender }}

        </div>

        {% endif %}

        {% endfor %}

    </div>

    <div class="col-3 right">
        <!-- placeholder div -->
    </div>
</div>








{% endblock %}

templates/friends.html
{% extends 'base.html' %}

{% block custom_javascript %}
<script>
    $(document).ready(function () {
        // adding the top margin of our outer gray box of the friend list
        $(".contact-inside").first().css("margin-top", "2px");
    });
</script>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-3">
        <!-- placeholder div -->
    </div>

    <div class="col-6">
        <h1 style="text-align: center; margin-bottom: 5px">Friends</h1>
        {% for contact in contacts %}

        <form action="/write_message/" method="post">
            {% csrf_token %}

            <div class="outer-grey-block">

                <div class="contact-inside">
                    <input type='hidden' name="receiver_email" value="{{ contact.email}}"/>
                    <p style="text-align:left;">
                       <span style="text-align: center;
                                vertical-align: middle;
                        line-height: 40px; margin-left: 5px  ">{{contact.name}}
                       </span>
                       <span style="float:right;"> <button class="friends-send-message-button dark-orange-bottom" type="submit">Send Message</button>

                        </span>
                    </p>
                </div>
            </div>
        </form>
        {% endfor %}
    </div>

    <div class="col-3 right">
        <!-- placeholder div -->
    </div>
</div>


{% endblock %}

templates/login.html
{% extends 'auth_base.html' %}

{% block custom_javascript %}
    <script>
         $(document).ready(function(){
             $("#id_username").attr('placeholder', 'Enter email address');
             $("#id_password").attr('placeholder', 'Enter password');

        });
    </script>
{% endblock %}

{% block content %}

 <ul class="auth-topnav" id="">
  <li><a href="/register/" class="auth-inactive">Sign Up</a></li>
  <li><a href="/login/" class="auth-active">Login</a></li>
</ul>


<div class="row">
<div class="col-3 col-m-3">
<!-- placeholder div -->
</div>

<div class="col-6 col-m-9">

        <h2 class="auth-login-top-heading centered-text">Welcome back!</h2>
        <h3 class="auth-sub-heading centered-text">Please Login</h3>
{% if form.errors %}
    <p>Your email and password didn't match. Please try again.</p>
{% endif %}
<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
    {% csrf_token %}

    <div class="container center-input-form">

        {{ form.username }}
        <!-- <input type="text" placeholder="Enter Email adress" name="uname" required> -->

        {{ form.password }}
        <!--<input type="password" placeholder="Enter Password" name="psw" required> -->
        <input type="hidden" name="next" value="{{ next }}"/>

        <div class="centered-button">
            <button class="auth-login-button dark-orange-bottom" type="submit">Login</button>
        </div>
        <br>
        <div class="no-paragraph-margin">
            <p class="centered-text"> Already A User? </p>
             <a class="centered-link" href="/register/"> Go To Sign Up </a>
        </div>

    </div>

</form>
</div>

<div class="col-3 col-m-12">
<!-- placeholder div -->
</div>

</div>




{% endblock %}

templates/messages.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-3">
        <!-- placeholder div -->
    </div>

    <div class="col-6">
        <h1 style="text-align: center">Messages</h1>


        {% for conversation in conversations_with_messages %}
        <div class="create-space-on-mobile-view"></div>

        <form action="/write_message/" method="post">
            {% csrf_token %}


            <!-- We decide if we have to add the "new" badge or not -->
            {% with conversation.messages|last as last_message %}
            {% if last_message.was_read or last_message.from_email == user.email %}
            <div class="col-4 join-message-col-left-or-top">
                <div class="message-block">
                    <div class="message-inner-block center-message-name">
                        <span class="centered-name-in-message-box"><a
                                href="/conversation/{{ conversation.conversation_id }}"> {{conversation.conversation_partner}}</a></span>
                    </div>
                </div>
            </div>

            {% else %}
            <div class="col-4 join-message-col-left-or-top badge1" data-badge="New">
                <div class="message-block">
                    <div class="message-inner-block center-message-name">
                        <span class="centered-name-in-message-box"><a
                                href="/conversation/{{ conversation.conversation_id }}"> {{conversation.conversation_partner}}</a></span>
                    </div>
                </div>
            </div>

            {% endif %}

            {% endwith %}


            <div class="col-8 join-message-col-right-or-top">
                <div class="message-block">
                    <div class="message-inner-block message-text-presentation">

                        <div class="col-8 join-message-col-left-or-top">
                            {% with conversation.messages|last as last_message %}

                            {% if last_message.was_read or last_message.from_email == user.email %}
                                <a class="centered-message-link" href="/conversation/{{ conversation.conversation_id }}">
                                  {{  last_message.message_text }} </a>
                            {% else %}
                                <a class="centered-message-link bold" href="/conversation/{{ conversation.conversation_id }}">
                                  {{  last_message.message_text }} </a>
                            {% endif %}

                            {% endwith %}
                        </div>

                        <div class="col-4 join-message-col-right-or-top">
                            <button class="message-reply-button dark-orange-bottom" type="submit"> Reply</button>
                        </div>

                    </div>
                    <input type="hidden" name="receiver_email" value="{{ conversation.conversation_partner_email }}">
                    <input type="hidden" name="conversation_id" value="{{ conversation.conversation_id }}">


                </div>
            </div>
        </form>

        {% endfor %}

    </div>

    <div class="col-3 right">
        <!-- placeholder div -->
    </div>

</div>


{% endblock %}

templates/new_message.html
{% extends 'base.html' %}

{% block custom_javascript %}
<script>
     $(document).ready(function(){
        console.log('adding outer margin to top div now ');
        $(".id_message_text").attr('placeholder', 'Write your message here...');    });

</script>
{% endblock %}



{% block content %}

<div class="row">
    <div class="col-3 move-down-back-button-on-small-screen">
        <a class="messages-back-link"  href="/"><< Back</a>
    </div>

    <div class="col-6 new-message" id="new-message-content">
        <h1 style="text-align: center;">Send Message</h1>
        <h4 style="text-align: center;">to {{ contact_name }}</h4>

        <form method="post" action="/send_message/">
            {% csrf_token %}
                <div style="text-align: center">
                    <div class="descriptionarea">
                    {{ message_form.as_p }}

                <span class="buttonfortxtarea">
                    <button class= "new-message-send-button dark-orange-bottom">Send Message</button></span>

                </div>
</div>


    </form>



       </div>


    </div>

    <div class="col-3 right">
        <!-- placeholder div -->
    </div>

</div>

{% endblock %}

templates/register.html
{% extends "auth_base.html" %}
{% load i18n %}
{% block custom_javascript %}
    <script>
         $(document).ready(function(){
             $("#id_username").attr('placeholder', '* Your Name');
             $("#id_email").attr('placeholder', '* Your email address');
             $("#id_password1").attr('placeholder', '*Enter password');

        });
    </script>
{% endblock %}

{% block content %}
 <ul class="auth-topnav" id="">
  <li><a href="/register/" class="auth-active">Sign Up</a></li>
  <li><a href="/login/" class="auth-inactive">Login</a></li>
</ul>


<div class="row">
<div class="col-3 col-m-3">
<!-- placeholder div -->
</div>

<div class="col-6 col-m-9">

        <h2 class="auth-signup-top-heading centered-text">Sign Up for BasketFriends!</h2>
        <h3 class="auth-sub-heading centered-text">Please enter your details</h3>

<form method="post" action="">
    {% csrf_token %}

    <div class="container center-input-form">

      {{ form.username }}

      {{ form.email }}

      {{ form.password1 }}

        <div class="centered-button">
            <button class="auth-register-button dark-blue-bottom" type="submit">Sign Up</button>
        </div>

    </div>

</form>
</div>

<div class="col-3 col-m-12">
<!-- placeholder div -->
</div>

</div>
{% endblock %}